### ISSUE TITLE
Pseudo modify file "lib/modules/5.10.83/kernel/net/netfilter/*.ko" does not exist in source filesystem. Ignoring. 

### ISSUE THREAD

**Issue by pojiro** [b5g-ex/nerves_system_stm32mp157c_odyssey#2]
The warning described in the title is displayed when running mix firmware on mac.
This is caused by the mac file system's case-insensitive handling of file names.

For example, the netfilter kernel modules include the following, which are distinguished as separate files in linux.

```
/lib/modules/5.10.83/kernel/net/netfilter/xt_DSCP.ko
/lib/modules/5.10.83/kernel/net/netfilter/xt_dscp.ko
```

However, the mac described earlier does not distinguish between the two.
The result of the mix firmware should be the following,

```
iex(19)> cmd "find / -iname xt_dscp.ko" # this firmware was made on ubuntu
/lib/modules/5.10.83/kernel/net/netfilter/xt_DSCP.ko
/lib/modules/5.10.83/kernel/net/netfilter/xt_dscp.ko
```

But on the mac described above, it will look like this

```
iex(1)> cmd "find / -iname xt_dscp.ko" # this firmware was made on mac
/lib/modules/5.10.83/kernel/net/netfilter/xt_DSCP.ko
```

**Since these netfileter modules are not used, there is no effect on the operation.
And if it is a module that is not used, we think it should not be included in this system in the first place (future work).**

---
all `Ignoring`s are below

```
Copying rootfs_overlay: /Users/takase/research/B5G_ex/hetero_beam/stm32mp1_nerves/_build/stm32mp157c_odyssey_dev/nerves/rootfs_overlay
Copying rootfs_overlay: /Users/takase/research/B5G_ex/hetero_beam/stm32mp1_nerves/rootfs_overlay
Pseudo modify file "lib/modules/5.10.83/kernel/net/netfilter/xt_dscp.ko" does not exist in source filesystem.  Ignoring.
Pseudo modify file "lib/modules/5.10.83/kernel/net/netfilter/xt_hl.ko" does not exist in source filesystem.  Ignoring.
Pseudo modify file "lib/modules/5.10.83/kernel/net/netfilter/xt_rateest.ko" does not exist in source filesystem.  Ignoring.
Pseudo modify file "lib/modules/5.10.83/kernel/net/netfilter/xt_tcpmss.ko" does not exist in source filesystem.  Ignoring.
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on /Users/takase/research/B5G_ex/hetero_beam/stm32mp1_nerves/_build/_nerves-tmp/combined.squashfs, block size 131072.
```

**Comment by pojiro** [comment]
@takasehideki 

I think [v0.1.2](https://github.com/b5g-ex/nerves_system_stm32mp157c_odyssey/releases/tag/v0.1.2) might resolve this issue, 'cause I removed configs which relates to xt_*.ko. Could you confirm it when you are free?

**Comment by takasehideki** [comment]
@pojiro Cc @kikuzo @kikuyuta 
Thanks so much! I've confirmed v0.1.2 could solve this issue in my environment. So I close this issue 🎉
